### ISSUE TITLE
Make query expression optional in de-substitution

### ISSUE THREAD

**Issue by daliwali** [geraintluff/uri-templates#12]
When I have a template that looks like this:
```
{/type,ids,field}{?query*}
```
And I try to match it against a URI without the `?` symbol:
```
/user/1,2,3/posts
```
It explodes and I just get an empty object `{}`. But when I add the `?` symbol to the end of the URI, it works (matches type, ids, field). The caveat to appending the `?` is that now I get `{'': ''}` in the `query` object that is extraneous so I delete it. 

In substitution, if I pass in nothing as `query`, this works, but somehow it's not optional in de-substitution.

**Comment by geraintluff** [comment]
Good point, that is unintuitive.  I'll have a look at a fix.

**Comment by daliwali** [comment]
:+1:
