### ISSUE TITLE
de-substitution from a url without any parameter values does not return a empty object

### ISSUE THREAD

**Issue by osvaldopina** [geraintluff/uri-templates#17]
De-substitution from a url without any parameter values does not return a empty object

    describe("Decode empty query ", function () {
        it('Must return a empty object', function () {
            var template = new UriTemplate('{?query}');

            var uri = '?';
            var guess = template.fromUri(uri);

            assert.isUndefined(guess['']);

        });
    });

**Comment by geraintluff** [comment]
Should be fixed in `v0.1.9` :)
