### ISSUE TITLE
Accepting PRs for ESM support?

### ISSUE THREAD

**Issue by brettz9** [geraintluff/uri-templates#28]
Would you be open to a PR to add an ESM export (presumably changing source to ESM and then exporting also as UMD)?

**Comment by brettz9** [comment]
The ESM syntax for exporting, e.g.., `export default X;` or `export {x};` do not work for CJS or UMD.

**Comment by geraintluff** [comment]
Hmm, OK.  Perhaps it could be in a separate `.mjs` file then.

It smells a bit bad to have almost-identical files like that, but I'm unlikely to do much (if any) further development on this library unless there's a major bug, so it's probably not a big deal.

In that case, a PR would be welcome!

**Comment by brettz9** [comment]
Thanks! I've submitted #29 . It now generates the UMD file from the ESM file, so there is not the code smell I think. And yes, I'd be happy to be added as a contributor (looking to follow whatever procedures you would like for review).

**Comment by brettz9** [comment]
Closed by #29.
